# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get latest CMake
      uses: lukka/get-cmake@v3.19.2

    - name: Install dependencies
      run: |
        command -v sudo &> /dev/null || (apt update && apt install sudo)
        sudo apt update && sudo apt install ninja-build libgl1-mesa-glx libgl1-mesa-dev libglew-dev ninja-build libusb-dev make python pkg-config g++-10 python3-pip libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev xtrans-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev xkb-data libxcb-dri3-dev uuid-dev libxcb-util-dev -y
        pip install conan

    - name: CMake
      run: |
        test -d build || mkdir build
        cd build
        export CC=/usr/bin/gcc-10
        export CXX=/usr/bin/g++-10
        cmake .. -G Ninja -Wno-dev -DCMAKE_BUILD_TYPE=Release

    - name: Ninja
      run: |
        cd build
        ninja
